### ISSUE TITLE
Emergency Contact: Populated New Contact and submitted - did not take me back to season page like the other sections did

### ISSUE THREAD

**Issue by kimbalinski** [FRCTeam238/MyTeam238#4]

**Comment by alexherreid** [comment]
That's correct- the relationships page, and the emer contact pages, don't redirect to the homepage when you submit data. This is done because on the season-specific pages, you can see if they're "complete" from the homepage. You can't see relationships/emer contacts on the homepage, so we don't redirect when they're submitted (and thus the page you stay on when you submit will show you what the update is that has been made).

Is the desired behavior to redirect to homepage in both of these cases?
